# https://hub.docker.com/_/postgres/
# Use postgres/etherscan-etherscan-etherscan credentials
# Deploy: docker-compose -f postgres.yml up
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: etherscan-etherscan-etherscan
    ports:
      - 18401:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 18402:8080